### PR TITLE
Catch all exceptions in WRB

### PR DESCRIPTION
**Pull request by Saibamen**
Like in `RESTRoutinen.cs`

### CODE REVIEW

**Comment by gdl-reif** [comment]
@Saibamen after reviewing it with René and Niklas, we decided to put this PR on hold until after the release as it needs more testing in the various clients.

**Comment by gdl-reif** [comment]
Converted to draft because it needs adjustments on the client sides, and we want more improvement for error handling @ewu-nma @Saibamen

**Comment by Saibamen** [comment]
@gdl-reif: I think this can be closed now because of https://github.com/gandalan/idas-client-libs/commit/391abee560ee2e42461b38f9403572fc9e953b24?

**Comment by gdl-reif** [comment]
@ewu-nma What do you think?

**Comment by ewu-nma** [comment]
yeah this can be closed

**Pull request closed without merging**
